model_params:
    history_num_frames_agents: 2
    future_num_frames: 15

    step_time: 0.1

    dropout: 0.1
    head_num: 8
    d_model: 128

    local_num_layers: 3
    global_num_layers: 6
    causal_num_layers: 3
    causal_len: 15
    causal_interval: 2

    lane_feat_dim: 13
    cross_feat_dim: 6
    ego_feat_dim: 2
    agent_feat_dim: 10
    act_dim: 3

    prev_weight: 0.3

    read_into_memory: True

    ignore_ego: True

    yaw_w: 1

    acc_w: 0.1
    control_w: 0.01
    lqr_iter: 1

    yaw_vel_w: 0.1
    yaw_acc_w: 0.1
    yaw_control_w:  0.000001

optimizer:

  learning_rate: 5e-4
  weight_decay: 1e-4
  warmup_steps: 10000

###################
## VectorNet Params
data_generation_params:
  # maximum number of other agents to take (if less will be padded)
  other_agents_num: 30
  # maximum distance from AoI for another agent to be picked
  max_agents_distance: 50
  # Parameters defining which and how many lanes to be retrieved
  lane_params:
    # maximum number of lanes to take into account
    # if less they will be padded; if more the closest to AoI are picked
    max_num_lanes: 30
    # max number of points per lane
    max_points_per_lane: 20
    # max number of points per crosswalk
    max_points_per_crosswalk: 20
    # maximum radius around the AoI for which we retrieve
    max_retrieval_distance_m: 35
    # max number of crosswalks
    max_num_crosswalks: 20

  centroid_std: 2
  dist_enhanced: True

train_data_loader:
    shuffle: True
    batch_size: 128


val_data_loader:
    shuffle: False
    batch_size: 256

eval:
  num_scenes_to_unroll: 1024
  batch_size: 64

log_dir: exp
exp_name: nuplan
data_type: nuplan
seed: 42
